mysql:
  host: "127.0.0.1"
  user: "root"
  password: ""
  database: "my_server"

players:
  enabled: false
  table: "players"

ranks:
  enabled: false
  table: "players"
  permissions:
    2:
      - "command.ban"
    1:
      - "command.mute"
      - "command.kick"
    0:
      - "chat.message"

online-players:
  enabled: false
  table: "online_players"
  update-interval: 5

contributors:
  enabled: false
  table: "contributors"
  # TODO

commands-filter:
  enabled: false
  allowed-commands:
    - "home"
    - "sethome"
    - "spawn"
  not-allowed-message: "Unknown command: /{COMMAND}"
